from Code.Z import Util


class RegWorkMap:
    iso: str
    name: str
    border: str
    elo: int
    assoc: list

    donePV: str

    def __str__(self):
        s = ""
        for x in dir(self):
            if not x.startswith("_"):
                v = getattr(self, x)
                s += f"[{x}:{v!s}]"
        return s

    def save(self):
        dic = {}
        for name, value in Util.list_vars_values(self):
            dic[name] = value
        return dic

    def restore(self, dic):
        for k, v in dic.items():
            setattr(self, k, v)


def ld_countries(mapa):
    dic_filtros = {
        "Africa": [
            "gw",
            "zm",
            "ci",
            "eh",
            "cm",
            "eg",
            "cg",
            "za",
            "ao",
            "cd",
            "ga",
            "gn",
            "et",
            "gm",
            "zw",
            "cv",
            "gh",
            "rw",
            "tz",
            "gq",
            "na",
            "ne",
            "ng",
            "tn",
            "re",
            "lr",
            "ls",
            "tg",
            "td",
            "er",
            "ly",
            "bf",
            "dj",
            "sl",
            "bi",
            "bj",
            "cf",
            "bw",
            "dz",
            "yt",
            "sz",
            "mg",
            "ma",
            "ke",
            "ss",
            "ml",
            "km",
            "st",
            "mu",
            "mw",
            "sh",
            "so",
            "sn",
            "mr",
            "sc",
            "ug",
            "mz",
            "sd",
        ],
        "WorldMap": None,
    }
    filtro = dic_filtros[mapa]
    lista = []
    for iso, name, border, elo, assoc in (
            ("ad", _("Andorra"), ["fr", "es"], 2252, []),
            ("ae", _("United Arab Emirates"), ["qa", "om", "sa"], 2292, []),
            ("af", _("Afghanistan"), ["cn", "uz", "ir", "tm", "tj", "pk"], 1975, []),
            ("al", _("Albania"), ["me", "gr", "mk", "rs"], 2336, []),
            ("am", _("Armenia"), ["tr", "ge", "az", "ir"], 2655, []),
            ("ao", _("Angola"), ["zm", "na", "cg", "cd"], 2214, []),
            ("ar", _("Argentina"), ["py", "bo", "uy", "br", "cl"], 2540, []),
            (
                    "at",
                    _("Austria"),
                    ["ch", "de", "it", "li", "sk", "cz", "si", "hu"],
                    2490,
                    [],
            ),
            (
                    "au",
                    _("Australia"),
                    ["ki", "nz", "vu", "fj", "id", "pg"],
                    2451,
                    ["cc", "cx", "hm"],
            ),
            ("az", _("Azerbaijan"), ["ru", "tr", "ir", "am", "ge", "az"], 2629, []),
            ("ba", _("Bosnia and Herzegovina"), ["hr", "me", "rs"], 2511, []),
            ("bd", _("Bangladesh"), ["mm", "in"], 2397, []),
            ("be", _("Belgium"), ["lu", "fr", "de", "nl"], 2501, []),
            ("bf", _("Burkina Faso"), ["ci", "ml", "ne", "bj", "tg", "gh"], 1500, []),
            ("bg", _("Bulgaria"), ["ro", "tr", "gr", "mk", "rs"], 2605, []),
            ("bh", _("Bahrain"), ["sa"], 1935, []),
            ("bi", _("Burundi"), ["rw", "tz", "cd"], 1758, []),
            ("bj", _("Benin"), ["tg", "bf", "ne", "ng"], 1500, []),
            ("bn", _("Brunei Darussalam"), ["my"], 1961, []),
            ("bo", _("Bolivia"), ["py", "ar", "pe", "br", "cl"], 2245, []),
            (
                    "br",
                    _("Brazil"),
                    ["py", "co", "ve", "sr", "bo", "gy", "gf", "ar", "pe", "uy"],
                    2519,
                    [],
            ),
            ("bs", _("Bahamas"), ["us", "cu"], 1746, []),
            ("bt", _("Bhutan"), ["cn", "in"], 1686, []),
            ("bw", _("Botswana"), ["na", "zw", "za", "zm"], 2141, []),
            ("by", _("Belarus"), ["lv", "ru", "lt", "ua", "pl"], 2571, []),
            ("bz", _("Belize"), ["gt", "mx"], 1500, []),
            ("ca", _("Canada"), ["dk", "us"], 2499, []),
            (
                    "cd",
                    _("Congo, the Democratic Republic of the"),
                    ["zm", "rw", "tz", "ss", "cg", "bi", "ao", "cf", "ug"],
                    1500,
                    [],
            ),
            (
                    "cf",
                    _("Central African Republic"),
                    ["cm", "ss", "cg", "cd", "td", "sd"],
                    1500,
                    [],
            ),
            ("cg", _("Congo"), ["ga", "cd", "cm", "ao", "cf"], 1500, []),
            ("ch", _("Switzerland"), ["fr", "de", "it", "li", "at"], 2504, []),
            ("ci", _("Ivory Coast"), ["gn", "bf", "lr", "ml", "gh"], 1500, []),
            ("cl", _("Chile"), ["ar", "ws", "bo", "pe"], 2447, []),
            ("cm", _("Cameroon"), ["gq", "cg", "cf", "ng", "ga", "td"], 1989, []),
            (
                    "cn",
                    _("China"),
                    [
                        "ru",
                        "mn",
                        "kg",
                        "af",
                        "mm",
                        "la",
                        "jp",
                        "vn",
                        "bt",
                        "kp",
                        "tj",
                        "in",
                        "np",
                        "kz",
                        "ph",
                        "pk",
                    ],
                    2688,
                    ["tw", "hk", "mo"],
            ),
            ("co", _("Colombia"), ["ve", "pa", "ec", "br", "pe"], 2440, []),
            ("cr", _("Costa Rica"), ["ni", "pa"], 2305, []),
            ("cu", _("Cuba"), ["jm", "mx", "ht", "bs"], 2589, []),
            ("cv", _("Cabo Verde"), ["mr"], 1500, []),
            ("cy", _("Cyprus"), ["lb", "sy", "tr", "gb"], 2116, []),
            ("cz", _("Czech Republic"), ["sk", "de", "at", "pl"], 2582, []),
            (
                    "de",
                    _("Germany"),
                    ["be", "fr", "ch", "nl", "dk", "cz", "lu", "at", "pl"],
                    2630,
                    [],
            ),
            ("dj", _("Djibouti"), ["et", "so", "er"], 1500, []),
            ("dk", _("Denmark"), ["ca", "de", "is"], 2541, ["gl", "fo"]),
            ("dm", _("Dominica"), ["ht"], 1500, []),
            ("do", _("Dominican Republic"), ["ht"], 2315, []),
            ("dz", _("Algeria"), ["ma", "eh", "ml", "ne", "tn", "mr", "ly"], 2320, []),
            ("ec", _("Ecuador"), ["co", "pe"], 2326, []),
            ("ee", _("Estonia"), ["lv", "ru"], 2455, []),
            ("eg", _("Egypt"), ["ps", "sd", "il", "ly"], 2466, []),
            ("eh", _("Western Sahara"), ["ma", "dz", "mr"], 1500, []),
            ("er", _("Eritrea"), ["et", "dj", "sd"], 1500, []),
            ("es", _("Spain"), ["fr", "ma", "ad", "pt"], 2592, []),
            ("et", _("Ethiopia"), ["dj", "ke", "ss", "so", "er", "sd"], 1808, []),
            ("fi", _("Finland"), ["ru", "se", "no"], 2444, ["ax"]),
            ("fj", _("Fiji"), ["nz", "au", "vu"], 1855, []),
            ("fm", _("Micronesia, Federated States of"), ["pg", "mh"], 1500, []),
            (
                    "fr",
                    _("France"),
                    ["be", "ch", "nl", "ad", "mc", "de", "it", "lu", "es"],
                    2661,
                    ["gp", "nc", "re", "pf", "tf", "pm", "wf", "mf", "fx", "yt", "mq"],
            ),
            ("ga", _("Gabon"), ["cg", "gq", "cm", "st"], 1500, []),
            (
                    "gb",
                    _("United Kingdom"),
                    ["ie", "fr"],
                    2622,
                    [
                        "ck",
                        "vc",
                        "gs",
                        "ag",
                        "gg",
                        "im",
                        "io",
                        "gi",
                        "lc",
                        "tv",
                        "nf",
                        "sh",
                        "pn",
                        "vg",
                        "bb",
                        "bl",
                        "bm",
                        "je",
                        "fk",
                        "kn",
                        "tc",
                        "ai",
                        "gd",
                        "ms",
                        "sb",
                        "ky",
                    ],
            ),
            ("ge", _("Georgia"), ["ru", "az", "am", "tr"], 2590, []),
            ("gf", _("French Guiana"), ["sr", "lu", "br", "mc"], 1500, []),
            ("gh", _("Ghana"), ["tg", "bf", "ci"], 1855, []),
            ("gm", _("Gambia"), ["sn"], 1917, []),
            ("gn", _("Guinea"), ["gw", "ci", "ml", "lr", "sn", "sl"], 1500, []),
            ("gq", _("Equatorial Guinea"), ["ga", "cm"], 1500, []),
            ("gr", _("Greece"), ["bg", "tr", "al", "mk"], 2552, []),
            ("gt", _("Guatemala"), ["hn", "sv", "bz", "mx"], 2219, []),
            ("gw", _("Guinea-Bissau"), ["gn", "sn"], 1500, []),
            ("gy", _("Guyana"), ["sr", "ve", "br"], 1831, []),
            ("hn", _("Honduras"), ["ni", "gt", "sv"], 2175, []),
            ("hr", _("Croatia"), ["me", "si", "rs", "ba", "hu"], 2583, []),
            ("ht", _("Haiti"), ["do", "dm", "cu"], 1959, []),
            ("hu", _("Hungary"), ["rs", "hr", "sk", "si", "at", "ro", "ua"], 2655, []),
            ("id", _("Indonesia"), ["au", "tl", "my", "pg"], 2414, []),
            ("ie", _("Ireland"), ["is", "gb"], 2390, []),
            ("il", _("Israel"), ["ps", "eg", "jo", "lb", "sy"], 1513, []),
            ("in", _("India"), ["bd", "cn", "mm", "lk", "bt", "mv", "np", "pk"], 2660, []),
            ("iq", _("Iraq"), ["sy", "ir", "tr", "jo", "kw", "sa"], 2304, []),
            (
                    "ir",
                    _("Iran, Islamic Republic of"),
                    ["af", "iq", "tr", "am", "tm", "pk", "az"],
                    2482,
                    [],
            ),
            ("is", _("Iceland"), ["ie", "dk"], 2514, []),
            ("it", _("Italy"), ["va", "fr", "ch", "mt", "si", "at", "sm"], 2551, []),
            ("jm", _("Jamaica"), ["cu"], 2153, []),
            ("jo", _("Jordan"), ["iq", "sy", "sa", "il", "ps"], 2197, []),
            ("jp", _("Japan"), ["kr", "cn"], 2251, []),
            ("ke", _("Kenya"), ["ss", "et", "ug", "so", "tz"], 2061, []),
            ("kg", _("Kyrgyzstan"), ["kz", "tj", "cn", "uz"], 2265, []),
            ("kh", _("Cambodia"), ["vn", "th", "la"], 1500, []),
            ("ki", _("Kiribati"), ["nz", "au", "vu"], 1500, []),
            ("km", _("Comoros"), ["mg", "mz"], 1500, []),
            (
                    "kp",
                    _("Korea, Democratic People's Republic of"),
                    ["kr", "cn", "ru"],
                    1500,
                    [],
            ),
            ("kr", _("Korea, Republic of"), ["kp", "jp"], 2050, []),
            ("kw", _("Kuwait"), ["iq", "sa"], 1943, []),
            ("kz", _("Kazakhstan"), ["ru", "tm", "kg", "cn", "uz"], 2492, []),
            (
                    "la",
                    _("Lao People's Democratic Republic"),
                    ["mm", "kh", "cn", "th", "vn"],
                    1500,
                    [],
            ),
            ("lb", _("Lebanon"), ["sy", "cy", "il"], 2192, []),
            ("li", _("Liechtenstein"), ["ch", "at"], 2041, []),
            ("lk", _("Sri Lanka"), ["in"], 2137, []),
            ("lr", _("Liberia"), ["gn", "ci", "sl"], 1500, []),
            ("ls", _("Lesotho"), ["za"], 1583, []),
            ("lt", _("Lithuania"), ["lv", "ru", "by", "pl"], 2477, []),
            ("lu", _("Luxembourg"), ["be", "fr", "de", "gf"], 2323, []),
            ("lv", _("Latvia"), ["ee", "ru", "lt", "by"], 2525, []),
            ("ly", _("Libya"), ["eg", "ne", "tn", "dz", "td", "sd"], 2191, []),
            ("ma", _("Morocco"), ["dz", "eh", "es"], 2322, []),
            ("mc", _("Monaco"), ["gf", "fr"], 2310, []),
            ("md", _("Moldova, Republic of"), ["to", "ro", "ua"], 2462, []),
            ("me", _("Montenegro"), ["hr", "rs", "al", "ba"], 2447, []),
            ("mg", _("Madagascar"), ["mu", "sc", "km", "mz"], 2058, []),
            ("mh", _("Marshall Islands"), ["fm"], 1500, []),
            ("mk", _("Macedonia"), ["rs", "bg", "al", "gr"], 2455, []),
            ("ml", _("Mali"), ["bf", "ci", "ne", "dz", "sn", "mr", "gn"], 2139, []),
            ("mm", _("Myanmar"), ["bd", "la", "cn", "th", "in"], 1954, []),
            ("mn", _("Mongolia"), ["ru", "cn"], 2417, []),
            ("mr", _("Mauritania"), ["ml", "dz", "sn", "cv", "eh"], 1946, []),
            ("mt", _("Malta"), ["tn", "it"], 2095, []),
            ("mu", _("Mauritius"), ["mg"], 1891, []),
            ("mv", _("Maldives"), ["in"], 1650, []),
            ("mw", _("Malawi"), ["zm", "tz", "mz"], 1784, []),
            ("mx", _("Mexico"), ["cu", "gt", "us", "bz"], 2435, []),
            ("my", _("Malaysia"), ["bn", "ph", "sg", "id", "th"], 2283, []),
            (
                    "mz",
                    _("Mozambique"),
                    ["sz", "mg", "tz", "zm", "za", "km", "mw", "zw"],
                    1858,
                    [],
            ),
            ("na", _("Namibia"), ["zm", "bw", "za", "ao"], 1886, []),
            ("ne", _("Niger"), ["bf", "ml", "bj", "ng", "dz", "td", "ly"], 1500, []),
            ("ng", _("Nigeria"), ["td", "cm", "bj", "ne"], 2224, []),
            ("ni", _("Nicaragua"), ["cr", "hn"], 2233, []),
            ("nl", _("Netherlands"), ["be", "fr", "de"], 2642, ["aw", "cw", "bq", "sx"]),
            ("no", _("Norway"), ["fi", "se", "ru"], 2559, ["bv", "sj"]),
            ("np", _("Nepal"), ["cn", "in"], 2070, []),
            ("nr", _("Nauru"), ["pg"], 1500, []),
            ("nz", _("New Zealand"), ["ws", "fj", "au", "ki"], 2296, ["tk", "nu"]),
            ("om", _("Oman"), ["ye", "sa", "ae"], 2062, []),
            ("pa", _("Panama"), ["cr", "co"], 2160, []),
            ("pe", _("Peru"), ["bo", "co", "ec", "br", "cl"], 2520, []),
            ("pg", _("Papua New Guinea"), ["nr", "au", "id", "fm"], 1966, []),
            ("ph", _("Philippines"), ["my", "cn", "vn", "pw"], 2529, []),
            ("pk", _("Pakistan"), ["in", "ir", "cn", "af"], 1931, []),
            ("pl", _("Poland"), ["de", "sk", "cz", "lt", "ua", "by"], 2636, []),
            ("ps", _("Palestine, State of"), ["eg", "jo", "il"], 2798, []),
            ("pt", _("Portugal"), ["es"], 2393, []),
            ("pw", _("Palau"), ["ph"], 1761, []),
            ("py", _("Paraguay"), ["ar", "br", "bo"], 2367, []),
            ("qa", _("Qatar"), ["sa", "ae"], 2118, []),
            ("ro", _("Romania"), ["md", "bg", "ua", "rs", "hu"], 2562, []),
            (
                    "rs",
                    _("Serbia"),
                    ["me", "bg", "ba", "rs", "hr", "al", "mk", "hu", "ro"],
                    2572,
                    [],
            ),
            (
                    "ru",
                    _("Russian Federation"),
                    [
                        "cn",
                        "no",
                        "ee",
                        "mn",
                        "lt",
                        "us",
                        "lv",
                        "ge",
                        "kp",
                        "kz",
                        "fi",
                        "az",
                        "ua",
                        "by",
                        "pl",
                    ],
                    2740,
                    [],
            ),
            ("rw", _("Rwanda"), ["ug", "tz", "bi", "cd"], 1723, []),
            (
                    "sa",
                    _("Saudi Arabia"),
                    ["om", "ae", "iq", "bh", "ye", "qa", "jo", "kw"],
                    1952,
                    [],
            ),
            ("sc", _("Seychelles"), ["mg", "so"], 1725, []),
            ("sd", _("Sudan"), ["ss", "eg", "cf", "et", "td", "er", "ly"], 2112, []),
            ("se", _("Sweden"), ["fi", "no"], 2537, []),
            ("sg", _("Singapore"), ["my"], 2375, []),
            ("si", _("Slovenia"), ["hr", "hu", "at", "it"], 2540, []),
            ("sk", _("Slovakia"), ["cz", "ua", "at", "pl", "hu"], 2498, []),
            ("sl", _("Sierra Leone"), ["gn", "lr"], 1500, []),
            ("sm", _("San Marino"), ["it"], 2000, []),
            ("sn", _("Senegal"), ["gw", "gn", "gm", "mr", "ml"], 1705, []),
            ("so", _("Somalia"), ["sc", "et", "dj", "so", "ke"], 1500, []),
            ("sr", _("Suriname"), ["gf", "gy", "br"], 2026, []),
            ("ss", _("South Sudan"), ["ke", "cf", "cd", "et", "ug", "sd"], 1500, []),
            ("st", _("Sao Tome and Principe"), ["ga"], 1781, []),
            ("sv", _("El Salvador"), ["gt", "hn"], 2200, []),
            (
                    "sy",
                    _("Syrian Arab Republic"),
                    ["lb", "iq", "tr", "cy", "jo", "il"],
                    2267,
                    [],
            ),
            ("sz", _("Swaziland"), ["za", "mz"], 1500, []),
            ("td", _("Chad"), ["cm", "ne", "ng", "cf", "ly", "sd"], 1500, []),
            ("tg", _("Togo"), ["bf", "bj", "gh"], 1771, []),
            ("th", _("Thailand"), ["mm", "kh", "my", "la"], 2190, []),
            ("tj", _("Tajikistan"), ["uz", "kg", "cn", "af"], 2304, []),
            ("tl", _("Timor-Leste"), ["id"], 1500, []),
            ("tm", _("Turkmenistan"), ["kz", "ir", "uz", "af"], 2390, []),
            ("tn", _("Tunisia"), ["mt", "dz", "ly"], 2297, []),
            ("to", _("Tonga"), ["md", "ua"], 1500, []),
            (
                    "tr",
                    _("Turkey"),
                    ["sy", "bg", "gr", "iq", "ir", "am", "cy", "ge", "az"],
                    2544,
                    [],
            ),
            ("tt", _("Trinidad and Tobago"), ["ve"], 2128, []),
            (
                    "tz",
                    _("Tanzania, United Republic of"),
                    ["zm", "rw", "ke", "bi", "cd", "mw", "ug", "mz"],
                    1751,
                    [],
            ),
            (
                    "ua",
                    _("Ukraine"),
                    ["ru", "md", "hu", "sk", "to", "ro", "by", "pl"],
                    2690,
                    [],
            ),
            ("ug", _("Uganda"), ["ss", "rw", "tz", "ke", "cd"], 2212, []),
            (
                    "us",
                    _("United States"),
                    ["ru", "ca", "mx", "bs"],
                    2641,
                    ["gu", "vi", "as", "pr", "um", "mp"],
            ),
            ("uy", _("Uruguay"), ["ar", "br"], 2312, []),
            ("uz", _("Uzbekistan"), ["tj", "kz", "tm", "kg", "af"], 2512, []),
            ("va", _("Holy See (Vatican City State)"), ["it"], 1500, []),
            ("ve", _("Venezuela"), ["tt", "co", "gy", "br"], 2413, []),
            ("vn", _("Viet Nam"), ["ph", "kh", "cn", "la"], 2504, []),
            ("vu", _("Vanuatu"), ["fj", "au", "ki"], 1500, []),
            ("ws", _("Samoa"), ["nz", "cl"], 1500, []),
            ("ye", _("Yemen"), ["om", "sa"], 2217, []),
            ("za", _("South Africa"), ["sz", "na", "bw", "ls", "zw", "mz"], 2312, []),
            ("zm", _("Zambia"), ["tz", "na", "ao", "cd", "mw", "bw", "zw", "mz"], 2234, []),
            ("zw", _("Zimbabwe"), ["zm", "bw", "za", "mz"], 2186, []),
    ):
        if filtro:
            if iso not in filtro:
                continue
            border = [biso for biso in border if biso in filtro]
            assoc = [biso for biso in assoc if biso in filtro]
        alm = RegWorkMap()
        alm.iso = iso
        alm.name = name
        alm.border = border
        alm.elo = elo
        alm.assoc = assoc

        lista.append(alm)

    dic = {alm.iso: alm for alm in lista}
    dic_names = {alm.iso: alm.name for alm in lista}
    return dic, dic_names
